# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.synced_folder  ".", "/vagrant", disabled: false
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.5"

    slave.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "slave.yaml"
      ansible.become = true
    end
  end

  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.50.4"

    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "master.yaml"
    end
  end
end
